name: Mocha Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elasticsearch:7.17.4
        env:
          discovery.type: single-node
          xpack.security.enabled: "false"
        ports:
          - 9200:9200
        options: >-
          --health-cmd "curl http://localhost:9200"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build
      run: npm run build

    - name: Unit Tests
      run: npm run test-unit
      env:
        LOG_LEVEL: debug

    - name: Mock Tests
      run: npm run test-mock
      env:
        LOG_LEVEL: debug