name: Mocha Tests

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'

    - name: Build
      run: npm run build

    - name: Launch elastic
      run: npm run elastic-start

    - name: Tests
      run: npm run test
      env:
        LOG_LEVEL: debug

    - name: Stop elastic
      run: npm run elastic-stop